apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
data:
  DB_HOST: "users-db"
  DB_NAME: "Db.Users"
  ASPNETCORE_ENVIRONMENT: "Development"
  ACCEPT_EULA: "Y"
  MSSQL_PID: "Developer"
