apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: fiapstore
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=users-db;Port=5432;Database=Db.Users;Username=postgres;Password=rooot1234!!"
  Jwt__Key: "IkV6/I+/6WtC4xTRDjLMdwWl0jkt6UAU2R0NUwsL7fI="
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "rooot1234!!"
  POSTGRES_DB: "Db.Users"
