apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      initContainers:
        - name: wait-for-users-db
          image: mcr.microsoft.com/mssql-tools:latest
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: DB_PASSWORD
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for SQL Server..."
              until /opt/mssql-tools/bin/sqlcmd \
                -S users-db,1433 \
                -U sa \
                -P "$DB_PASSWORD" \
                -Q "SELECT 1" \
                -C > /dev/null 2>&1
              do
                sleep 5
              done
      containers:
        - name: users-api
          image: users-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: DB_NAME
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: users-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: users-secret
                  key: DB_PASSWORD
                  
                  
